### PR TITLE
Set (multiple) collabora remote_configs

### PR DESCRIPTION
**Pull request by DecaTec**
Resolves https://github.com/sunweaver/nextcloud-high-performance-backend-setup/issues/73

### CODE REVIEW

**Review by sunweaver — APPROVED** [review]
LGTM

**Comment by sunweaver** [comment]
rebased and pushed to "main" branch, thus closing

@DecaTec for future PRs it would help if you allowed project maintainers of this project to push to your PR branches. Often I want to rebase your PR against latest changes on the main branch of this repo and for that I normally need to force-push to the PR branch.

Anyway, I now pushed to the "main" branch directly, but then dumb Github won't realize this here and will auto-mark this PR as merged...

**Comment by sunweaver** [comment]
Git log reference: 24a7c0cbd3adeebedf4ec262f05998ecebb3b46d

**Comment by DecaTec** [comment]
> rebased and pushed to "main" branch, thus closing
> 
> @DecaTec for future PRs it would help if you allowed project maintainers of this project to push to your PR branches. Often I want to rebase your PR against latest changes on the main branch of this repo and for that I normally need to force-push to the PR branch.
> 
> Anyway, I now pushed to the "main" branch directly, but then dumb Github won't realize this here and will auto-mark this PR as merged...

Will do so in the future. Thx for the hint!

**Pull request closed without merging**
